import { FormEvent, useEffect, useState } from 'react'
import { X } from 'lucide-react'
import type { Page } from './WorkspacePage'

type Option={id:number;name:string;kind?:string}
const configs:Partial<Record<Page,{endpoint:string;fields:[string,string,string,string?][]}>>={
  Packages:{endpoint:'/api/packages',fields:[['name','Package name','text','5/5 Mbps'],['advertised_down_mbps','Download Mbps','number'],['advertised_up_mbps','Upload Mbps','number']]},
  'IP pools':{endpoint:'/api/ip-pools',fields:[['name','Pool name','text'],['kind','Type: private or public','text','private'],['start_address','First IPv4 address','text'],['end_address','Last IPv4 address','text']]},
  'Routers & sites':{endpoint:'/api/routers',fields:[['name','Router name','text'],['host','Loopback / management IP','text'],['site_name','Site name','text'],['api_username','API username','text','admin'],['api_password','API password','password']]},
}
export default function CrudModal({page,onClose,onCreated}:{page:Page;onClose:()=>void;onCreated:()=>void}){const config=configs[page];const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [packages,setPackages]=useState<Option[]>([]);const [pools,setPools]=useState<Option[]>([]);useEffect(()=>{if(page==='Subscribers')Promise.all([fetch('/api/packages').then(r=>r.json()),fetch('/api/ip-pools').then(r=>r.json())]).then(([a,b])=>{setPackages(a);setPools(b)})},[page]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const raw=Object.fromEntries(new FormData(event.currentTarget));const body:Record<string,unknown>={...raw,enabled:true};for(const key of ['advertised_down_mbps','advertised_up_mbps','package_id','pool_id'])if(key in body)body[key]=Number(body[key]);try{const endpoint=page==='Subscribers'?'/api/subscribers':config!.endpoint;const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const detail=(await response.json()).detail;throw new Error(typeof detail==='string'?detail:'Please check every field.')}onCreated();onClose()}catch(error){setError(error instanceof Error?error.message:'Could not save record')}finally{setBusy(false)}}return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>{page==='Packages'?'Create package':page==='IP pools'?'Add IP pool':page==='Routers & sites'?'Register MikroTik':'Add subscriber'}</h2><p>Saved securely on this WISP server.</p></div><button type="button" onClick={onClose}><X size={18}/></button></div>{page==='Subscribers'?<><label>PPPoE username<input name="username" required/></label><label>PPPoE password<input name="password" type="password" required/></label><label>Package<select name="package_id" required>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>IP pool<select name="pool_id" required>{pools.map(p=><option key={p.id} value={p.id}>{p.name} ({p.kind})</option>)}</select></label></>:config?.fields.map(([name,label,type,placeholder])=><label key={name}>{label}<input name={name} type={type} placeholder={placeholder} defaultValue={placeholder} required/></label>)}{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></div>}
