import { FormEvent, useEffect, useState } from 'react'
import { Edit3, Plus, Users, X } from 'lucide-react'
import CrudModal from './CrudModal'

const ipNumber=(value:string)=>value.split('.').reduce((n,part)=>n*256+Number(part),0)
export default function SubscriberPage({query}:{query:string}){
  const [users,setUsers]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[pools,setPools]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[add,setAdd]=useState(false),[notice,setNotice]=useState(''),[sort,setSort]=useState<{key:string;asc:boolean}>({key:'username',asc:true})
  const load=()=>Promise.all([fetch('/api/subscribers').then(r=>r.json()),fetch('/api/packages').then(r=>r.json()),fetch('/api/ip-pools').then(r=>r.json())]).then(([u,p,i])=>{setUsers(u);setPackages(p);setPools(i)})
  useEffect(()=>{load()},[])
  const poolFor=(user:any)=>pools.find(p=>ipNumber(user.framed_ip_address)>=ipNumber(p.start_address)&&ipNumber(user.framed_ip_address)<=ipNumber(p.end_address))
  async function status(user:any){await fetch(`/api/subscribers/${user.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:user.status==='suspended'?'active':'suspended'})});setNotice(user.status==='suspended'?'Service restored and connection refreshed':'Subscriber suspended at 8k/8k');load()}
  const value=(u:any,key:string)=>key==='package'?packages.find(p=>p.id===u.package_id)?.name??'':key==='ip'?ipNumber(u.framed_ip_address):u[key]
  const shown=users.filter(u=>JSON.stringify(u).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const x=value(a,sort.key),y=value(b,sort.key);const result=typeof x==='number'?x-y:String(x).localeCompare(String(y));return sort.asc?result:-result})
  const headings:[string,string][]=[['username','PPPoE username'],['display_name','Customer'],['package','Package'],['ip','IP allocation'],['status','Status']]
  const choose=(key:string)=>setSort(current=>({key,asc:current.key===key?!current.asc:true}))
  return <section className="workspace-page"><div className="heading"><div><p>WISP workspace</p><h1>Subscribers</h1><span>Manage PPPoE credentials, packages, IP allocation and UISP links.</span></div><button className="primary" onClick={()=>setAdd(true)}><Plus size={17}/>Add subscriber</button></div>{notice&&<div className="notice">{notice}</div>}{add&&<CrudModal page="Subscribers" onClose={()=>setAdd(false)} onCreated={load}/>}<article className="table-card"><div className="table-title"><div className="page-icon"><Users/></div><div><b>Subscribers</b><span>{shown.length} records</span></div></div><div className="table-wrap"><table><thead><tr>{headings.map(([key,label])=><th key={key}><button className="sort-head" onClick={()=>choose(key)}>{label}{sort.key===key?(sort.asc?' ↑':' ↓'):''}</button></th>)}<th>Actions</th></tr></thead><tbody>{shown.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.display_name}</td><td>{packages.find(p=>p.id===u.package_id)?.name??'Unknown'}</td><td>{u.framed_ip_address}<small className="cell-note">{poolFor(u)?.name??u.ip_kind}</small></td><td>{u.status}</td><td><div className="row-actions"><button className="secondary" onClick={()=>setEdit({...u,pool_id:poolFor(u)?.id})}><Edit3 size={14}/> Edit</button><button className="secondary" onClick={()=>status(u)}>{u.status==='suspended'?'Restore':'Suspend'}</button></div></td></tr>)}</tbody></table></div></article>{edit&&<EditSubscriber user={edit} packages={packages} pools={pools} close={()=>setEdit(null)} saved={()=>{setEdit(null);setNotice('PPPoE updated; any active connection was disconnected to apply it');load()}}/>}</section>
}
function EditSubscriber({user,packages,pools,close,saved}:{user:any;packages:any[];pools:any[];close:()=>void;saved:()=>void}){const [error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const raw=Object.fromEntries(new FormData(e.currentTarget));const body:any={username:raw.username,uisp_client_id:raw.uisp_client_id||null,uisp_link_confirmed:Boolean(raw.uisp_client_id),package_id:Number(raw.package_id)};if(raw.password)body.password=raw.password;if(Number(raw.pool_id)!==Number(user.pool_id))body.pool_id=Number(raw.pool_id);const r=await fetch(`/api/subscribers/${user.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){setError((await r.json()).detail??'Could not save');return}saved()}return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>Edit subscriber</h2><p>PPPoE changes force an immediate reconnect.</p></div><button type="button" onClick={close}><X/></button></div><label>PPPoE username<input name="username" defaultValue={user.username} required/></label><label>New password<input name="password" type="password" placeholder="Leave blank to keep existing"/></label><label>Package<select name="package_id" defaultValue={user.package_id}>{packages.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>IP allocation pool<select name="pool_id" defaultValue={user.pool_id}>{pools.filter(p=>p.enabled).map(p=><option key={p.id} value={p.id}>{p.name} · {p.kind} · {p.total-p.used} available</option>)}</select></label><p className="form-help">Changing the pool automatically assigns the next free address and releases the previous address.</p><label>UISP customer ID<input name="uisp_client_id" defaultValue={user.uisp_client_id??''} placeholder="Link later when UISP customer exists"/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save and reconnect</button></div></form></div>}
