"""Generate the dedicated FreeRADIUS files backend from Net2Net's database.

This is deliberately a local-files backend for the first offline deployment.
It supports PAP, CHAP, MS-CHAPv1 and MS-CHAPv2 through FreeRADIUS's standard
modules, while Net2Net remains the source of users, packages and NAS clients.
"""
from pathlib import Path

from cryptography.fernet import InvalidToken

from sqlmodel import Session, select

from .config import get_settings
from .database import engine
from .models import Package, Router, Status, Subscriber
from .security import decrypt_secret


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def sync(config_dir: str = "/etc/freeradius/3.0") -> None:
    settings = get_settings()
    root = Path(config_dir)
    authorize = root / "mods-config/files/authorize"
    clients = root / "clients.conf"
    authorize.parent.mkdir(parents=True, exist_ok=True)

    with Session(engine) as session:
        packages = {item.id: item for item in session.exec(select(Package)).all()}
        subscribers = session.exec(select(Subscriber)).all()
        routers = session.exec(select(Router).where(Router.enabled == True)).all()  # noqa: E712

    user_lines = ["# Generated by Net2Net. Do not edit; regenerate from the portal.\n"]
    for subscriber in subscribers:
        if subscriber.status == Status.DISABLED:
            continue
        try:
            password = decrypt_secret(subscriber.password_ciphertext)
        except InvalidToken:
            # A pre-persistent development key cannot be recovered after a
            # container replacement.  Do not let that stale test record block
            # every valid imported subscriber from authenticating.
            continue
        package = packages.get(subscriber.package_id)
        rate = "8k/8k" if subscriber.status == Status.SUSPENDED else (
            f"{package.provisioned_up_mbps:g}M/{package.provisioned_down_mbps:g}M" if package else "8k/8k"
        )
        user_lines.extend([
            f'"{_escape(subscriber.username)}" Cleartext-Password := "{_escape(password)}"\n',
            f"\tFramed-IP-Address := {subscriber.framed_ip_address},\n",
            f'\tMikrotik-Rate-Limit := "{rate}"\n\n',
        ])
    authorize.write_text("".join(user_lines), encoding="utf-8")

    client_lines = [
        "# Generated by Net2Net.\n",
        "client localhost {\n\tipaddr = 127.0.0.1\n\tsecret = testing123\n\trequire_message_authenticator = yes\n}\n\n",
    ]
    # RouterOS can source RADIUS from a loopback or LAN address rather than
    # its API address.  Each deployment can opt into its own private CIDR.
    if settings.radius_client_network:
        client_lines.append(
            f'client net2net_private_wisp {{\n\tipaddr = {_escape(settings.radius_client_network)}\n'
            f'\tsecret = "{_escape(settings.radius_shared_secret)}"\n\trequire_message_authenticator = yes\n}}\n\n'
        )
    seen: set[str] = set()
    for router in routers:
        for address in (router.host, router.radius_source_address):
            if not address or address in seen:
                continue
            seen.add(address)
            name = "net2net_" + address.replace(".", "_").replace(":", "_")
            client_lines.extend([
                f"client {name} {{\n", f"\tipaddr = {address}\n",
                f'\tsecret = "{_escape(settings.radius_shared_secret)}"\n', "\trequire_message_authenticator = yes\n", "}\n\n",
            ])
    clients.write_text("".join(client_lines), encoding="utf-8")


if __name__ == "__main__":
    sync()
