from .schemas import AccountStatus, DashboardSummary, Package, Router, Subscriber

PACKAGES = [
    Package(
        id=1,
        name="5/5 Mbps",
        advertised_down_mbps=5,
        advertised_up_mbps=5,
        provisioned_down_mbps=6,
        provisioned_up_mbps=6,
        subscribers=18,
    ),
    Package(
        id=2,
        name="10/10 Mbps",
        advertised_down_mbps=10,
        advertised_up_mbps=10,
        provisioned_down_mbps=11,
        provisioned_up_mbps=11,
        subscribers=31,
    ),
    Package(
        id=3,
        name="20/20 Mbps",
        advertised_down_mbps=20,
        advertised_up_mbps=20,
        provisioned_down_mbps=21,
        provisioned_up_mbps=21,
        subscribers=24,
    ),
    Package(
        id=4,
        name="50/20 Mbps",
        advertised_down_mbps=50,
        advertised_up_mbps=20,
        provisioned_down_mbps=51,
        provisioned_up_mbps=21,
        subscribers=9,
    ),
]

SUBSCRIBERS = [
    Subscriber(
        id=1,
        username="demo.home@example.co.za",
        display_name="Demo Home",
        status=AccountStatus.ACTIVE,
        package="20/20 Mbps",
        ip_address="10.250.0.12",
        ip_kind="Private",
        site="North Ridge",
        uisp_client_id="91",
        online=True,
    ),
    Subscriber(
        id=2,
        username="guesthouse@example.co.za",
        display_name="Guesthouse Main",
        status=AccountStatus.ACTIVE,
        package="50/20 Mbps",
        ip_address="203.0.113.25",
        ip_kind="Public",
        site="Town POP",
        uisp_client_id="55",
        online=True,
    ),
    Subscriber(
        id=3,
        username="pending@example.co.za",
        display_name="New Installation",
        status=AccountStatus.UNLINKED,
        package="10/10 Mbps",
        ip_address="10.250.0.40",
        ip_kind="Private",
        site="Farm Sector",
        online=False,
    ),
    Subscriber(
        id=4,
        username="suspended@example.co.za",
        display_name="Suspended Demo",
        status=AccountStatus.SUSPENDED,
        package="8k/8k",
        ip_address="10.250.0.21",
        ip_kind="Private",
        site="North Ridge",
        uisp_client_id="46",
        online=True,
    ),
]

ROUTERS = [
    Router(
        id=1,
        name="North Ridge",
        loopback_ip="10.250.250.5",
        site="North Ridge",
        online=True,
        active_sessions=28,
    ),
    Router(
        id=2,
        name="Town POP",
        loopback_ip="10.250.250.9",
        site="Town POP",
        online=True,
        active_sessions=41,
    ),
    Router(
        id=3,
        name="Farm Sector",
        loopback_ip="10.250.250.14",
        site="Farm Sector",
        online=False,
        active_sessions=0,
    ),
]

SUMMARY = DashboardSummary(
    subscribers=82,
    online=69,
    suspended=3,
    unlinked=7,
    routers_online=2,
    routers_total=3,
    public_ips_used=11,
    public_ips_total=30,
    private_ips_used=71,
    private_ips_total=220,
)
